#Program 2: Guess the number
#Generate 1 random number (0-100)
#Ask the user to guess the number
#Display “Greater than” if the inputed number is greater than the random number
#Display “Less than” if the inputed number is less than the random number
#Repeat asking the user until the random number has been guessed correctly.

import random
import time
from colorama import Fore, Back, Style

def programintro ():
    print ("Hello and welcome to 'Guess the Number'!")
    time.sleep (1)
    print ("All you have to do is to guess the number which was randomly generated by the game.")
    time.sleep (1)
    print ("Don't worry we'll give you hints on whether the number that you guessed is higher or lower than the number generated.")
    time.sleep (1)
    print ("That's all, good luck player!")

def enternumber ():
    print ("The program has successfully generated a number! It's your turn to guess it!")
    answer = (random.randint (0, 100))
    userinput = int(input("Enter your guess here: "))
    while userinput == answer:
        if userinput > answer:
            print (Fore.YELLOW + "The number you've guessed is greater than the generated number. Please try again.")
            userinput = int(input("Enter your guess here: "))
        elif userinput < answer:
            print (Fore.BLUE + "The number you've guessed is less than the generated number. Please try again.")  
            userinput = int(input("Enter your guess here: "))
        else:
            print (Fore.GREEN + "Congratulations! You guessed the correct number!")
