#Program 2: Guess the number
#Generate 1 random number (0-100)
#Ask the user to guess the number
#Display “Greater than” if the inputed number is greater than the random number
#Display “Less than” if the inputed number is less than the random number
#Repeat asking the user until the random number has been guessed correctly.

import random
import time
from colorama import Fore, Back, Style

def programintro ():
    print ("Hello and welcome to 'Guess the Number'!")
    time.sleep (1)
    print ("All you have to do is to guess the number which was randomly generated by the game.")
    time.sleep (1)
    print ("Don't worry we'll give you hints on whether the number that you guessed is higher or lower than the number generated.")
    time.sleep (1)
    print ("That's all, good luck player!")


